-- ============================================================
-- Pharmacy Management System — Database Schema
-- Compatible with H2 and PostgreSQL
-- ============================================================

DROP TABLE IF EXISTS sale_items;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS medicine_batches;
DROP TABLE IF EXISTS medicines;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS users;

-- 1. USERS
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)     NOT NULL UNIQUE,
    password    VARCHAR(255)    NOT NULL,
    full_name   VARCHAR(100)    NOT NULL,
    role        VARCHAR(20)     NOT NULL DEFAULT 'PHARMACIST',
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'PHARMACIST'))
);

-- 2. SUPPLIERS
CREATE TABLE suppliers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    phone       VARCHAR(20),
    email       VARCHAR(100),
    address     VARCHAR(500),
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. MEDICINES
CREATE TABLE medicines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    category        VARCHAR(50),
    manufacturer    VARCHAR(100),
    unit_price      DECIMAL(10,2)   NOT NULL,
    supplier_id     BIGINT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_medicines_price CHECK (unit_price > 0),
    CONSTRAINT fk_medicines_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL
);

CREATE INDEX idx_medicines_name ON medicines(name);
CREATE INDEX idx_medicines_supplier ON medicines(supplier_id);

-- 4. MEDICINE BATCHES
CREATE TABLE medicine_batches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id     BIGINT          NOT NULL,
    batch_number    VARCHAR(50)     NOT NULL,
    expiry_date     DATE            NOT NULL,
    quantity        INTEGER         NOT NULL,
    purchase_price  DECIMAL(10,2),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_batches_quantity CHECK (quantity >= 0),
    CONSTRAINT uq_medicine_batch UNIQUE (medicine_id, batch_number),
    CONSTRAINT fk_batches_medicine FOREIGN KEY (medicine_id) REFERENCES medicines(id) ON DELETE CASCADE
);

CREATE INDEX idx_batches_medicine ON medicine_batches(medicine_id);
CREATE INDEX idx_batches_expiry ON medicine_batches(expiry_date);

-- 5. SALES
CREATE TABLE sales (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    total_amount    DECIMAL(10,2)   NOT NULL,
    sale_date       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sales_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_sales_date ON sales(sale_date);

-- 6. SALE ITEMS
CREATE TABLE sale_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     BIGINT          NOT NULL,
    batch_id    BIGINT          NOT NULL,
    quantity    INTEGER         NOT NULL,
    unit_price  DECIMAL(10,2)   NOT NULL,
    subtotal    DECIMAL(10,2)   NOT NULL,
    CONSTRAINT chk_sale_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_sale_items_price CHECK (unit_price >= 0),
    CONSTRAINT chk_sale_items_subtotal CHECK (subtotal >= 0),
    CONSTRAINT fk_sale_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
    CONSTRAINT fk_sale_items_batch FOREIGN KEY (batch_id) REFERENCES medicine_batches(id)
);

CREATE INDEX idx_sale_items_sale ON sale_items(sale_id);
CREATE INDEX idx_sale_items_batch ON sale_items(batch_id);
